name: PR â†’ develop checks

on:
  pull_request:
    branches: [ develop ]

jobs:
  enforce-and-check-develop:
    name: enforce-and-check-develop
    runs-on: ubuntu-latest

    steps:
      - name: Enforce merge direction
        if: github.event_name == 'pull_request'
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"

          if [[ "$BASE" != "develop" ]]; then
            echo "Only PRs into develop are allowed"
            exit 1
          fi

          BUILD_FRONTEND=false
          BUILD_BACKEND=false

          if [[ "$HEAD" == frontend/* ]]; then
            BUILD_FRONTEND=true
          elif [[ "$HEAD" == backend/* ]]; then
            BUILD_BACKEND=true
          elif [[ "$HEAD" == feature/* || "$HEAD" == fix/* ]]; then
            BUILD_FRONTEND=true
            BUILD_BACKEND=true
          else
            echo "Invalid branch name"
            exit 1
          fi

          echo "build_frontend=$BUILD_FRONTEND" >> "$GITHUB_OUTPUT"
          echo "build_backend=$BUILD_BACKEND" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Frontend)
        if: steps.detect.outputs.build_frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend install dependencies
        if: steps.detect.outputs.build_frontend == 'true'
        run: npm ci
        working-directory: frontend-put-together

      - name: Frontend lint
        if: steps.detect.outputs.build_frontend == 'true'
        run: npm run lint
        working-directory: frontend-put-together

      - name: Frontend build
        if: steps.detect.outputs.build_frontend == 'true'
        run: npm run build
        working-directory: frontend-put-together

      - name: Backend Docker build
        if: steps.detect.outputs.build_backend == 'true'
        run: docker build backend-put-together

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Backend build
        run: dotnet build
        working-directory: backend-put-together
