name: PR → develop checks

on:
  pull_request:
    branches: [develop]

jobs:
  enforce-and-check:
    name: enforce-and-check
    runs-on: ubuntu-latest

    steps:
      - name: Enforce merge direction
        if: github.event_name == 'pull_request'
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"

          if [[ "$BASE" == "develop" && ( "$HEAD" == feature/* || "$HEAD" == fix/* )]]; then
            exit 0
          fi

          echo "Only feature/* or fix/* → develop allowed"
          exit 1

      - uses: actions/checkout@v4
        
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend install dependencies
        run: npm ci
        working-directory: frontend-put-together

      - name: Frontend lint
        run: npm run lint
        working-directory: frontend-put-together

      - name: Frontend build
        run: npm run build
        working-directory: frontend-put-together
      
      - name: Backend Docker build
        run: docker build backend-put-together
