name: PR â†’ main checks

on:
  pull_request:
    branches: [main]

jobs:
  enforce-and-check-main:
    name: enforce-and-check-main
    runs-on: ubuntu-latest

    steps:
      - name: Enforce merge direction
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"

          if [[ "$BASE" != "main" || "$HEAD" != "develop" ]]; then
            echo "Only PRs from develop into main are allowed"
            exit 1
          fi

          echo "Merge direction valid"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend install dependencies
        run: npm ci
        working-directory: frontend-put-together

      - name: Frontend lint
        run: npm run lint
        working-directory: frontend-put-together

      - name: Frontend build
        run: npm run build
        working-directory: frontend-put-together

      - name: Backend Docker build
        run: docker build backend-put-together
